services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "85:80/tcp"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'password'
      DNS1: '1.1.1.2'
      DNS2: '1.0.0.2'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
